{
//=========Macro generated from canvas: canvas/canvas
//=========  (Fri Jun 27 14:00:28 2014) by ROOT version5.34/07
   TCanvas *canvas = new TCanvas("canvas", "canvas",1,1,600,576);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   canvas->SetHighLightColor(2);
   canvas->Range(-1.2,-0.2308809,6.8,0.9235235);
   canvas->SetFillColor(0);
   canvas->SetBorderMode(0);
   canvas->SetBorderSize(2);
   canvas->SetTickx(1);
   canvas->SetTicky(1);
   canvas->SetLeftMargin(0.15);
   canvas->SetBottomMargin(0.2);
   canvas->SetFrameFillStyle(0);
   canvas->SetFrameLineWidth(3);
   canvas->SetFrameBorderMode(0);
   canvas->SetFrameFillStyle(0);
   canvas->SetFrameLineWidth(3);
   canvas->SetFrameBorderMode(0);
   
   TH1F *Muon_pixHits_ = new TH1F("Muon_pixHits_","Muon_pixHits_",10,0,10);
   Muon_pixHits_->SetBinContent(0,0.006883065);
   Muon_pixHits_->SetBinContent(1,0.01141089);
   Muon_pixHits_->SetBinContent(2,0.01066655);
   Muon_pixHits_->SetBinContent(3,0.1375212);
   Muon_pixHits_->SetBinContent(4,0.6752586);
   Muon_pixHits_->SetBinContent(5,0.1466153);
   Muon_pixHits_->SetBinContent(6,0.01852742);
   Muon_pixHits_->SetBinContent(7,0.002463731);
   Muon_pixHits_->SetBinContent(8,0.0002732901);
   Muon_pixHits_->SetBinContent(9,1.922644e-05);
   Muon_pixHits_->SetMaximum(0.8080831);
   Muon_pixHits_->SetEntries(735183);
   Muon_pixHits_->SetLineWidth(2);
   Muon_pixHits_->GetXaxis()->SetTitle("Hits_{#mu}^{pixel}");
   Muon_pixHits_->GetXaxis()->SetRange(1,6);
   Muon_pixHits_->GetXaxis()->SetLabelFont(22);
   Muon_pixHits_->GetXaxis()->SetLabelSize(0.045);
   Muon_pixHits_->GetXaxis()->SetTitleSize(0.045);
   Muon_pixHits_->GetXaxis()->SetTitleFont(22);
   Muon_pixHits_->GetYaxis()->SetTitle("# of events (normalized to 1)");
   Muon_pixHits_->GetYaxis()->SetLabelFont(22);
   Muon_pixHits_->GetYaxis()->SetLabelSize(0.045);
   Muon_pixHits_->GetYaxis()->SetTitleSize(0.045);
   Muon_pixHits_->GetYaxis()->SetTitleOffset(1.45);
   Muon_pixHits_->GetYaxis()->SetTitleFont(22);
   Muon_pixHits_->GetZaxis()->SetLabelFont(42);
   Muon_pixHits_->GetZaxis()->SetLabelSize(0.035);
   Muon_pixHits_->GetZaxis()->SetTitleSize(0.035);
   Muon_pixHits_->GetZaxis()->SetTitleFont(42);
   Muon_pixHits_->Draw("");
   
   TH1F *Muon_pixHits_ = new TH1F("Muon_pixHits_","Muon_pixHits_",10,0,10);
   Muon_pixHits_->SetBinContent(0,0.05198055);
   Muon_pixHits_->SetBinContent(1,0.1361714);
   Muon_pixHits_->SetBinContent(2,0.02791091);
   Muon_pixHits_->SetBinContent(3,0.1776149);
   Muon_pixHits_->SetBinContent(4,0.5377432);
   Muon_pixHits_->SetBinContent(5,0.1038201);
   Muon_pixHits_->SetBinContent(6,0.0167395);
   Muon_pixHits_->SetBinContent(7,0.002079222);
   Muon_pixHits_->SetBinContent(8,0.0004933747);
   Muon_pixHits_->SetMaximum(0.8080831);
   Muon_pixHits_->SetEntries(29924);
   Muon_pixHits_->SetLineColor(2);
   Muon_pixHits_->SetLineWidth(2);
   Muon_pixHits_->GetXaxis()->SetTitle("Hits_{#mu}^{pixel}");
   Muon_pixHits_->GetXaxis()->SetRange(1,6);
   Muon_pixHits_->GetXaxis()->SetLabelFont(22);
   Muon_pixHits_->GetXaxis()->SetLabelSize(0.045);
   Muon_pixHits_->GetXaxis()->SetTitleSize(0.045);
   Muon_pixHits_->GetXaxis()->SetTitleFont(22);
   Muon_pixHits_->GetYaxis()->SetTitle("# of events (normalized to 1)");
   Muon_pixHits_->GetYaxis()->SetLabelFont(22);
   Muon_pixHits_->GetYaxis()->SetLabelSize(0.045);
   Muon_pixHits_->GetYaxis()->SetTitleSize(0.045);
   Muon_pixHits_->GetYaxis()->SetTitleOffset(1.45);
   Muon_pixHits_->GetYaxis()->SetTitleFont(22);
   Muon_pixHits_->GetZaxis()->SetLabelFont(42);
   Muon_pixHits_->GetZaxis()->SetLabelSize(0.035);
   Muon_pixHits_->GetZaxis()->SetTitleSize(0.035);
   Muon_pixHits_->GetZaxis()->SetTitleFont(42);
   Muon_pixHits_->Draw("same");
   
   TLegend *leg = new TLegend(0.72,0.72,0.89,0.89,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(22);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("Muon_pixHits_","H#rightarrowZZ","L");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Muon_pixHits_","QCD","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TPaveText *pt = new TPaveText(0.1577181,0.9,0.9580537,0.96,"brNDC");
   pt->SetBorderSize(0);
   pt->SetFillStyle(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(22);
   pt->SetTextSize(0.045);
   TText *text = pt->AddText(0.01,0.5,"CMS Simulation");
   text = pt->AddText(0.4,0.5,"#sqrt{s} = 8 TeV");
   pt->Draw();
   canvas->Modified();
   canvas->cd();
   canvas->SetSelected(canvas);
}
