{
//=========Macro generated from canvas: canvas/canvas
//=========  (Fri Jun 27 14:00:29 2014) by ROOT version5.34/07
   TCanvas *canvas = new TCanvas("canvas", "canvas",1,1,600,576);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   canvas->SetHighLightColor(2);
   canvas->Range(-1,-0.3301957,5.666667,1.320783);
   canvas->SetFillColor(0);
   canvas->SetBorderMode(0);
   canvas->SetBorderSize(2);
   canvas->SetTickx(1);
   canvas->SetTicky(1);
   canvas->SetLeftMargin(0.15);
   canvas->SetBottomMargin(0.2);
   canvas->SetFrameFillStyle(0);
   canvas->SetFrameLineWidth(3);
   canvas->SetFrameBorderMode(0);
   canvas->SetFrameFillStyle(0);
   canvas->SetFrameLineWidth(3);
   canvas->SetFrameBorderMode(0);
   
   TH1F *Electron_missing_hits_ = new TH1F("Electron_missing_hits_","Electron_missing_hits_",10,0,10);
   Electron_missing_hits_->SetBinContent(1,0.9631004);
   Electron_missing_hits_->SetBinContent(2,0.02524518);
   Electron_missing_hits_->SetBinContent(3,0.007021326);
   Electron_missing_hits_->SetBinContent(4,0.004289429);
   Electron_missing_hits_->SetBinContent(5,0.0003436808);
   Electron_missing_hits_->SetBinContent(6,2.924943e-05);
   Electron_missing_hits_->SetBinContent(7,1.462471e-06);
   Electron_missing_hits_->SetMaximum(1.155685);
   Electron_missing_hits_->SetEntries(683795);
   Electron_missing_hits_->SetLineWidth(2);
   Electron_missing_hits_->GetXaxis()->SetTitle("Hits^{missing}_{e}");
   Electron_missing_hits_->GetXaxis()->SetRange(1,5);
   Electron_missing_hits_->GetXaxis()->SetLabelFont(22);
   Electron_missing_hits_->GetXaxis()->SetLabelSize(0.045);
   Electron_missing_hits_->GetXaxis()->SetTitleSize(0.045);
   Electron_missing_hits_->GetXaxis()->SetTitleFont(22);
   Electron_missing_hits_->GetYaxis()->SetTitle("# of events (normalized to 1)");
   Electron_missing_hits_->GetYaxis()->SetLabelFont(22);
   Electron_missing_hits_->GetYaxis()->SetLabelSize(0.045);
   Electron_missing_hits_->GetYaxis()->SetTitleSize(0.045);
   Electron_missing_hits_->GetYaxis()->SetTitleOffset(1.45);
   Electron_missing_hits_->GetYaxis()->SetTitleFont(22);
   Electron_missing_hits_->GetZaxis()->SetLabelFont(42);
   Electron_missing_hits_->GetZaxis()->SetLabelSize(0.035);
   Electron_missing_hits_->GetZaxis()->SetTitleSize(0.035);
   Electron_missing_hits_->GetZaxis()->SetTitleFont(42);
   Electron_missing_hits_->Draw("");
   
   TH1F *Electron_missing_hits_ = new TH1F("Electron_missing_hits_","Electron_missing_hits_",10,0,10);
   Electron_missing_hits_->SetBinContent(1,0.9165697);
   Electron_missing_hits_->SetBinContent(2,0.05400924);
   Electron_missing_hits_->SetBinContent(3,0.01933185);
   Electron_missing_hits_->SetBinContent(4,0.009454263);
   Electron_missing_hits_->SetBinContent(5,0.0006349878);
   Electron_missing_hits_->SetBinContent(6,7.05542e-05);
   Electron_missing_hits_->SetMaximum(1.155685);
   Electron_missing_hits_->SetEntries(28349);
   Electron_missing_hits_->SetLineColor(2);
   Electron_missing_hits_->SetLineWidth(2);
   Electron_missing_hits_->GetXaxis()->SetTitle("Hits^{missing}_{e}");
   Electron_missing_hits_->GetXaxis()->SetRange(1,5);
   Electron_missing_hits_->GetXaxis()->SetLabelFont(22);
   Electron_missing_hits_->GetXaxis()->SetLabelSize(0.045);
   Electron_missing_hits_->GetXaxis()->SetTitleSize(0.045);
   Electron_missing_hits_->GetXaxis()->SetTitleFont(22);
   Electron_missing_hits_->GetYaxis()->SetTitle("# of events (normalized to 1)");
   Electron_missing_hits_->GetYaxis()->SetLabelFont(22);
   Electron_missing_hits_->GetYaxis()->SetLabelSize(0.045);
   Electron_missing_hits_->GetYaxis()->SetTitleSize(0.045);
   Electron_missing_hits_->GetYaxis()->SetTitleOffset(1.45);
   Electron_missing_hits_->GetYaxis()->SetTitleFont(22);
   Electron_missing_hits_->GetZaxis()->SetLabelFont(42);
   Electron_missing_hits_->GetZaxis()->SetLabelSize(0.035);
   Electron_missing_hits_->GetZaxis()->SetTitleSize(0.035);
   Electron_missing_hits_->GetZaxis()->SetTitleFont(42);
   Electron_missing_hits_->Draw("same");
   
   TLegend *leg = new TLegend(0.72,0.72,0.89,0.89,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(22);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("Electron_missing_hits_","H#rightarrowZZ","L");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Electron_missing_hits_","QCD","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TPaveText *pt = new TPaveText(0.1577181,0.9,0.9580537,0.96,"brNDC");
   pt->SetBorderSize(0);
   pt->SetFillStyle(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(22);
   pt->SetTextSize(0.045);
   TText *text = pt->AddText(0.01,0.5,"CMS Simulation");
   text = pt->AddText(0.4,0.5,"#sqrt{s} = 8 TeV");
   pt->Draw();
   canvas->Modified();
   canvas->cd();
   canvas->SetSelected(canvas);
}
