{
//=========Macro generated from canvas: canvas/canvas
//=========  (Fri Jun 27 14:00:28 2014) by ROOT version5.34/07
   TCanvas *canvas = new TCanvas("canvas", "canvas",1,1,600,576);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   canvas->SetHighLightColor(2);
   canvas->Range(-1,-0.168209,5.666667,0.672836);
   canvas->SetFillColor(0);
   canvas->SetBorderMode(0);
   canvas->SetBorderSize(2);
   canvas->SetTickx(1);
   canvas->SetTicky(1);
   canvas->SetLeftMargin(0.15);
   canvas->SetBottomMargin(0.2);
   canvas->SetFrameFillStyle(0);
   canvas->SetFrameLineWidth(3);
   canvas->SetFrameBorderMode(0);
   canvas->SetFrameFillStyle(0);
   canvas->SetFrameLineWidth(3);
   canvas->SetFrameBorderMode(0);
   
   TH1F *Muon_numberOfMatches_ = new TH1F("Muon_numberOfMatches_","Muon_numberOfMatches_",10,0,10);
   Muon_numberOfMatches_->SetBinContent(1,0.01545598);
   Muon_numberOfMatches_->SetBinContent(2,0.02824165);
   Muon_numberOfMatches_->SetBinContent(3,0.1683086);
   Muon_numberOfMatches_->SetBinContent(4,0.4512678);
   Muon_numberOfMatches_->SetBinContent(5,0.336726);
   Muon_numberOfMatches_->SetBinContent(6,8.570029e-05);
   Muon_numberOfMatches_->SetMaximum(0.5887315);
   Muon_numberOfMatches_->SetEntries(735183);
   Muon_numberOfMatches_->SetLineWidth(2);
   Muon_numberOfMatches_->GetXaxis()->SetTitle("Matched_{#mu}");
   Muon_numberOfMatches_->GetXaxis()->SetRange(1,5);
   Muon_numberOfMatches_->GetXaxis()->SetLabelFont(22);
   Muon_numberOfMatches_->GetXaxis()->SetLabelSize(0.045);
   Muon_numberOfMatches_->GetXaxis()->SetTitleSize(0.045);
   Muon_numberOfMatches_->GetXaxis()->SetTitleFont(22);
   Muon_numberOfMatches_->GetYaxis()->SetTitle("# of events (normalized to 1)");
   Muon_numberOfMatches_->GetYaxis()->SetLabelFont(22);
   Muon_numberOfMatches_->GetYaxis()->SetLabelSize(0.045);
   Muon_numberOfMatches_->GetYaxis()->SetTitleSize(0.045);
   Muon_numberOfMatches_->GetYaxis()->SetTitleOffset(1.45);
   Muon_numberOfMatches_->GetYaxis()->SetTitleFont(22);
   Muon_numberOfMatches_->GetZaxis()->SetLabelFont(42);
   Muon_numberOfMatches_->GetZaxis()->SetLabelSize(0.035);
   Muon_numberOfMatches_->GetZaxis()->SetTitleSize(0.035);
   Muon_numberOfMatches_->GetZaxis()->SetTitleFont(42);
   Muon_numberOfMatches_->Draw("");
   
   TH1F *Muon_numberOfMatches_ = new TH1F("Muon_numberOfMatches_","Muon_numberOfMatches_",10,0,10);
   Muon_numberOfMatches_->SetBinContent(1,0.3581072);
   Muon_numberOfMatches_->SetBinContent(2,0.4906096);
   Muon_numberOfMatches_->SetBinContent(3,0.05617565);
   Muon_numberOfMatches_->SetBinContent(4,0.05727844);
   Muon_numberOfMatches_->SetBinContent(5,0.03782917);
   Muon_numberOfMatches_->SetMaximum(0.5887315);
   Muon_numberOfMatches_->SetEntries(29924);
   Muon_numberOfMatches_->SetLineColor(2);
   Muon_numberOfMatches_->SetLineWidth(2);
   Muon_numberOfMatches_->GetXaxis()->SetTitle("Matched_{#mu}");
   Muon_numberOfMatches_->GetXaxis()->SetRange(1,5);
   Muon_numberOfMatches_->GetXaxis()->SetLabelFont(22);
   Muon_numberOfMatches_->GetXaxis()->SetLabelSize(0.045);
   Muon_numberOfMatches_->GetXaxis()->SetTitleSize(0.045);
   Muon_numberOfMatches_->GetXaxis()->SetTitleFont(22);
   Muon_numberOfMatches_->GetYaxis()->SetTitle("# of events (normalized to 1)");
   Muon_numberOfMatches_->GetYaxis()->SetLabelFont(22);
   Muon_numberOfMatches_->GetYaxis()->SetLabelSize(0.045);
   Muon_numberOfMatches_->GetYaxis()->SetTitleSize(0.045);
   Muon_numberOfMatches_->GetYaxis()->SetTitleOffset(1.45);
   Muon_numberOfMatches_->GetYaxis()->SetTitleFont(22);
   Muon_numberOfMatches_->GetZaxis()->SetLabelFont(42);
   Muon_numberOfMatches_->GetZaxis()->SetLabelSize(0.035);
   Muon_numberOfMatches_->GetZaxis()->SetTitleSize(0.035);
   Muon_numberOfMatches_->GetZaxis()->SetTitleFont(42);
   Muon_numberOfMatches_->Draw("same");
   
   TLegend *leg = new TLegend(0.72,0.72,0.89,0.89,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(22);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("Muon_numberOfMatches_","H#rightarrowZZ","L");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("Muon_numberOfMatches_","QCD","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TPaveText *pt = new TPaveText(0.1577181,0.9,0.9580537,0.96,"brNDC");
   pt->SetBorderSize(0);
   pt->SetFillStyle(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(22);
   pt->SetTextSize(0.045);
   TText *text = pt->AddText(0.01,0.5,"CMS Simulation");
   text = pt->AddText(0.4,0.5,"#sqrt{s} = 8 TeV");
   pt->Draw();
   canvas->Modified();
   canvas->cd();
   canvas->SetSelected(canvas);
}
